# server configuration
server:
  port: ${APPLICATION_PORT}
  address: ${APPLICATION_HOST}



# Spring configuration
spring:

  # gRPC server configuration
  grpc:
    server:
      port: ${GRPC_APPLICATION_PORT}
      host: ${GRPC_APPLICATION_HOST}

  # Application configuration
  application:
    name: Signum-Token-Service

  config:
    import: optional:file:dev.env[.properties]

  # Database configuration
  datasource:
    username: ${POSTGRES_HOST_USER}
    password: ${POSTGRES_HOST_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres

  jpa:
    hibernate:
      ddl-auto: update

  # Cache configuration
  cache:
    type: redis

  redis:
    ssl: false
    user: ${REDIS_HOST_USER}
    timeout: 2000ms
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_HOST_PASSWORD}

# Scheduled jobs configuration
scheduler:
  revoked-token-cleanup:
    #5 minutes
    delay: 5m

